### ISSUE TITLE
Don't wake on lan message send when connecting to a wifi ssid

### ISSUE THREAD

**Issue by emailforos** [Pozzoooo/WakeOnLan#1]
Hi.

I know there is no evolution of this app but I didn't find any free app able to wake up a pc when connecting to a wifi ssid except yours, but maybe you can take a look about it.

Please, I've got a problem: manually, it sends the magic packet but when using the wifi automation it doesn't work. If I press the wifi symbol in the advanced settings I see a message: "Could no get current ssid". I've checked permissions of the app and they are right.

Thanking your interest in at least checking my problem.

**Comment by Pozzoooo** [comment]
Hey,

It's actually over 6 year that I'm not using this app :(.
It might probably be related to some change on the way Android deals with Broadcasts or Services.

Giving it a quick look I can tell you that the best way to debug would be starting by NetworkConnectionReceiver.
That should be triggered when a network ssid is connected, but it could be that it is not being triggered because of some api change maybe?

I've updated the whole project so it can be compiled on current Android Studio version, all you need it clone and press the run button on Android Studio.
Feel free to share any findings :)

**Comment by emailforos** [comment]
Ok. Many Thanks.
I understand it's deprecated. 
I have almost zero knowledge in programming android apps (I only have small knowledge in php and C).
Thank you again for sharing your work.
